const token = JSON.stringify({
    "code": 0,
    "message": "success",
    "data": {
        "token": "kdkhfsklnnaljans,ankbaklnsdabkabskfabka"
    }
});

const info = JSON.stringify({
    "code": 0,
    "message": "success",
    "data": {
        "id": "1",
        "email": "admin@tenvee.com",
        "account": "admin",
        "username": "管理员",
        "password": "",
        "avatar": "https://img03.sogoucdn.com/app/a/100520021/683b7ec19c603a5b691bc0d73aa7c74a",
        "register_time": 1550199204000,
        "department": "eqwe",
        "telphone": "18774954941",
        "enabled": 0,
        "pwd_tag": 1,
        "permissionsCode": [
            "syslog:excel",
            "sysdata:list",
            "sysdata:excel",
            "sysdata:addtype",
            "sysdata:adddata",
            "sysdata:updatetype",
            "sysdata:updatedata",
            "sysdata:deletetype",
            "sysdata:deletedata",
            "sysdepartment:list",
            "sysdepartment:add",
            "sysdepartment:update",
            "sysdepartment:delete",
            "sysrole:roleuser",
            "sysrole:rolepower",
            "sysuser:list",
            "sysuser:add",
            "sysuser:update",
            "sysuser:delete",
            "sysrole:list",
            "sysrole:add",
            "sysrole:update",
            "sysrole:delete",
            "syslog:list",
            "sysuser:initpwd",
            "machinetype:list",
            "machinetype:add",
            "machinetype:update",
            "machinetype:delete",
            "machine:list",
            "machine:add",
            "machine:update",
            "machine:forbit",
            "manchine:log",
            "manchine:version",
            "machine:stepup",
            "team:list",
            "pack:list",
            "devicetype:list",
            "brand:list",
            "brand:add",
            "brand:update",
            "brand:forbit",
            "brand:log",
            "brand:version",
            "brand:stepup",
            "factory:list",
            "factory:add",
            "factory:update",
            "factory:delete",
            "factory:machine",
            "factory:device",
            "factory:brand",
            "integated:list",
            "integated:add",
            "integated:update",
            "integated:delete",
            "mainbrand:list",
            "mainproduce:list",
            "unit:list",
            "staff:list",
            "channel:list",
            "channel:add",
            "channel:update",
            "channel:delete",
            "whitelist:list",
            "whitelist: batchadd",
            "whitelist:add",
            "whitelist: batchdelete",
            "whitelist: delete"
        ],
        "userRoles": [
            "ROLE_ADMIN"
        ]
    }
});

exports.token = token;
exports.info = info;